### PR TITLE
Added Example code to upload to Weather Underground

### PR DESCRIPTION
**Pull request by danfein**
Added Example code to upload to Weather Underground
Also added dew point calculation, which meant adding fahrenheit/celsius vars, the dew point calculation wants C.
Also added deep sleep to shut everything down between sends, to help folks using batteries.
I am not a real programmer (I am a designer), please forgive any inelegance in my code.

### CODE REVIEW

**Comment by danfein** [comment]
Started getting some strange numbers from the shield, testing to make sure it isn't the code.

**Comment by danfein** [comment]
screen shot 2015-07-21 at 9 22 48 pm

**Comment by JoelEB** [comment]
Hi Dan, There seems to be an I2C issue on Particle's end. We are working with them to figure it out. It is not your additions. Thank you for your contribution. We will pull this in once the I2C issue has been resolved.

**Comment by danfein** [comment]
Thanks for the update, its good to know what is going on.
fwiw the first few reads are usually good. My example seems to be working out better now with the deep sleep between readings, so every reading is the first reading and is usually sane.

**Pull request closed without merging**
