### PR TITLE
Added Example code to upload to Weather Underground

### PR DESCRIPTION
**Pull request by danfein**
Added Example code to upload to Weather Underground. The 0.4.4 update seems to have sorted i2c out for the particle, the core works fine as well. 

More details: https://www.hackster.io/Dan/particle-photon-weather-station

### CODE REVIEW

**Comment by JoelEB** [comment]
Thanks for all your hard work! This is great!

**Comment by danfein** [comment]
Glad to help out, really happy to be able to contribute a tiny bit back.
I just noticed that you updated the other examples to use a unified library, should I update the Weather Underground example to use that as well?

**Comment by JoelEB** [comment]
If you have time, that would be great. The main reason for making that library was to account for the two different temp/humidity ICs that are going to be populated on the shield. I filed an issue on this repo that explains in more detail, but in short, we'll be phasing out the HTU21D for the Si7021. That library handles both without the end user having to distinguish between the two. I know you cleaned up the previous libraries a little. Some of the same changes could be made in that new library. I tried to eliminate redundancy, but it could get scrubbed some more. The library is over in [this repo](https://github.com/sparkfun/SparkFun_Photon_Weather_Shield_Particle_Library). If you would like to make any changes, please pull them into that repo, and I'll update these examples afterwards.

**Comment by danfein** [comment]
Sounds good, seems like a pretty straightforward change. I will pull down the new library and update the code, once it runs for a day or two and everything looks good I will put up the changes.

**Comment by wmjenk** [comment]
Dan and Joel,
I managed to get all of the Guide examples working with the new merged library using the Photon but I had to swap out the OneWire for the Particle-OneWire library and modify the spark-dallas-temperature library to call the Particle-OneWire found here:
https://github.com/balbano/OneWire-Particle
I am now able to use all of Joel's examples with the new Photon firmware-currently OneWire does not work with the latest firmware on the Photon.  Additionally, I was able to take Joel's Basic_Soil_Meters example and add Weather Underground updating using Joel's example but I added all the wind and rain data to the upload as well. I was not able to use Dan's deep sleep method to conserve the battery due to the wind and rain averaging functions that run while counting. I was able to use WiFi.on and WiFi.off before and after the uploads in the count timing routine Joel implemented to reduce power consumption between uploads. I am now working on adding a UV/ visible light and infrared light sensor to the package. Once I complete the project I can post the firmware if your interested.

**Comment by danfein** [comment]
@wmjenk I like your idea of turning off the wifi between sends as an alternative to deep sleep, I hadn't dealt with wind/rain sensors in this example, but both need constant monitoring (to calculate max gust/avg speed, and to count accumulation) The particle is pretty good on power, and with the radio off between sends I am sure batteries would still go a long way. I would be interested in seeing your code when you are all set to update my personal station :) the rain and wind sensors are a much more complicated problem then temp/pressure/humidity, with the moving parts and all.

**Comment by danfein** [comment]
@JoelEB I updated my code to follow the updated examples (new library, putting all the sensor reads in one function) I let it run on the bench and I didn't see any bad readings. I have it back outdoors for a field test, if that goes well I will send a pull request so the Weather Underground example will be up to date with the other examples.

**Comment by JoelEB** [comment]
@danfein Thanks again for all your work. I'm going to mention your Wunderground example in the Weather Shield tutorial. 
@wmjenk Thank you as well. If you want to add an example using light sensors, I'll be happy to add it to the repo, or you can issue a pull request.

**Comment by JoelEB** [comment]
@wmjenk I just went through all the examples again, and the regular OneWire library worked fine still. I also tried with the most recent version of OneWire, and it also works. I too had to use the OneWire-Particle library but that was at least a month ago. How old is the OneWire Library you were using?

**Comment by wmjenk** [comment]
@JoelEB It was one I downloaded as part of the Guide package linked from the Guide docs on the SparkFun web site. I will download your latest Guide firmware package from GitHub and try the OneWire lib included. I presume the OneWire was updated. It would be great to be able to use the OneWire that is integrated into the Web IDE. I let you know my results. If it works I will revert from Particle-OneWire to the current OneWire. BTW, I did get the SI1145 (from Adafruit) working with the Photon and will integrate it into my version of the "basic meters" Underground upload example. I will be using it shortly at Torrey Pines Elementary School in the school garden with k-5 students and teachers.

**Comment by wmjenk** [comment]
@JoelEB Yea your latest linked GitHub examples work with the included OneWire library. I will change my example to use your GitHub libraries. Thanks, Bill.

**Pull request merged**
